version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    ignore:
      - dependency-name: php
        update-types:
          - version-update:semver-major
